import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import { AuthProvider } from '@/context/auth-context';
import { ThemeProvider } from '@mui/material';
import theme from '@/styles/theme';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Dashboard HealthTech',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AuthProvider>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
